[package]
name = "wasmer-workspace"
version = "1.0.0-alpha3"
description = "Wasmer workspace"
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
repository = "https://github.com/wasmerio/wasmer"
license = "MIT"
edition = "2018"
publish = false
autoexamples = false

[dependencies]
wasmer = { version = "1.0.0-alpha3", path = "lib/api", default-features = false }
wasmer-compiler = { version = "1.0.0-alpha3", path = "lib/compiler" }
wasmer-compiler-cranelift = { version = "1.0.0-alpha3", path = "lib/compiler-cranelift", optional = true }
wasmer-compiler-singlepass = { version = "1.0.0-alpha3", path = "lib/compiler-singlepass", optional = true }
wasmer-compiler-llvm = { version = "1.0.0-alpha3", path = "lib/compiler-llvm", optional = true }
wasmer-engine = { version = "1.0.0-alpha3", path = "lib/engine" }
wasmer-engine-jit = { version = "1.0.0-alpha3", path = "lib/engine-jit", optional = true }
wasmer-engine-native = { version = "1.0.0-alpha3", path = "lib/engine-native", optional = true }
wasmer-wasi = { version = "1.0.0-alpha3", path = "lib/wasi", optional = true }
wasmer-wast = { version = "1.0.0-alpha3", path = "tests/lib/wast", optional = true }
wasmer-cache = { version = "1.0.0-alpha3", path = "lib/cache", optional = true }
wasmer-types = { version = "1.0.0-alpha3", path = "lib/wasmer-types" }
cfg-if = "0.1"

[workspace]
members = [
    "lib/api",
    "lib/cache",
    "lib/c-api",
    "lib/cli",
    "lib/compiler",
    "lib/compiler-cranelift",
    "lib/compiler-singlepass",
    "lib/compiler-llvm",
    "lib/emscripten",
    "lib/engine",
    "lib/engine-jit",
    "lib/engine-native",
    "lib/object",
    "lib/vm",
    "lib/wasi",
    "lib/wasi-experimental-io-devices",
    "lib/wasmer-types",
    "tests/lib/wast",
]
exclude = [
    "lib/deprecated",
]

[build-dependencies]
test-generator = { path = "tests/lib/test-generator" }
build-deps = "0.1.4"
anyhow = "1.0"
glob = "0.3"
rustc_version = "0.2"

[dev-dependencies]
anyhow = "1.0"
blake3 = "0.3"
criterion = "0.3"
lazy_static = "1.4"
wasmer-engine-dummy = { path = "tests/lib/engine-dummy" }
tempfile = "3.1"

[features]
# Don't add the compiler features in default, please add them on the Makefile
# since we might want to autoconfigure them depending on the availability on the host.
default = [
    "wat",
    "wast",
    "jit",
    "native",
    "cache",
    "wasi",
    # "emscripten",
]
engine = []
jit = [
    "wasmer-engine-jit",
    "engine",
]
native = [
    "wasmer-engine-native",
    "engine",
]
cache = ["wasmer-cache"]
wast = ["wasmer-wast"]
wasi = ["wasmer-wasi"]
# emscripten = ["wasmer-emscripten"]
wat = ["wasmer/wat"]
compiler = [
    "wasmer/compiler",
    "wasmer-compiler/translator",
    "wasmer-engine-jit/compiler",
    "wasmer-engine-native/compiler"
]
singlepass = [
    "wasmer-compiler-singlepass",
    "compiler",
]
cranelift = [
    "wasmer-compiler-cranelift",
    "compiler",
]
llvm = [
    "wasmer-compiler-llvm",
    "compiler",
]

# Testing features
test-singlepass = [
    "singlepass",
]
test-cranelift = [
    "cranelift",
]
test-llvm = [
    "llvm",
]

# Disable trap asserts in the WAST tests. This is useful for running the tests in a
# context where signal handling is a problem, such as tarpaulin for code coverage.
test-no-traps = ["wasmer-wast/test-no-traps"]

[profile.release.package.wasmer-c-api]
opt-level = "z"
codegen-units = 1

[[bench]]
name = "static_and_dynamic_functions"
harness = false

[[example]]
name = "early-exit"
path = "examples/early_exit.rs"
required-features = ["cranelift"]

[[example]]
name = "engine-jit"
path = "examples/engine_jit.rs"
required-features = ["cranelift"]

[[example]]
name = "engine-native"
path = "examples/engine_native.rs"
required-features = ["cranelift"]

[[example]]
name = "engine-headless"
path = "examples/engine_headless.rs"
required-features = ["cranelift"]

[[example]]
name = "cross-compilation"
path = "examples/engine_cross_compilation.rs"
required-features = ["cranelift"]

[[example]]
name = "compiler-singlepass"
path = "examples/compiler_singlepass.rs"
required-features = ["singlepass"]

[[example]]
name = "compiler-cranelift"
path = "examples/compiler_cranelift.rs"
required-features = ["cranelift"]

[[example]]
name = "compiler-llvm"
path = "examples/compiler_llvm.rs"
required-features = ["llvm"]

[[example]]
name = "exported-function"
path = "examples/exports_function.rs"
required-features = ["cranelift"]

[[example]]
name = "wasi"
path = "examples/wasi.rs"
required-features = ["cranelift", "wasi"]
